Ajout d'un filtre activité principale sur le tableau de suivi
betagouv/pitchou pull request #135
Opened 2024-12-18 15:36 UTC by Ynote

cf. carte Trello : https://trello.com/c/J5cnQE7E/353-tableau-de-suivi-ajouter-un-filtre-par-activit%C3%A9
+ https://trello.com/c/R3nGr2dU/399-quand-on-recherche-un-num%C3%A9ro-de-dossier-ds-dans-la-recherche-textuelle-avec-un-espace-le-dossier-nest-pas-retrouv%C3%A9

2025-01-02 16:10 UTC, Ynote commented on scripts/front-end/components/screens/SuiviInstruction.svelte
> +        const texteÀChercherSansEspace = _texteÀChercher.trim()
Cette partie correspond à la mini-modification de cette carte : https://trello.com/c/R3nGr2dU/399-quand-on-recherche-un-num%C3%A9ro-de-dossier-ds-dans-la-recherche-textuelle-avec-un-espace-le-dossier-nest-pas-retrouv%C3%A9

2025-01-02 16:12 UTC, Ynote commented on outils/recupère-schema-88444.js
> +/** @import {SchemaDémarcheSimplifiée} from '../scripts/types/démarches-simplifiées/schema.ts' */
@DavidBruant Est-ce que tu aurais une idée de pourquoi `tsc` me dit ça ?

2025-01-02 18:18 UTC, DavidBruant commented on outils/recupère-schema-88444.js
> +/** @import {SchemaDémarcheSimplifiée} from '../scripts/types/démarches-simplifiées/schema.ts' */
C'est un bug de TS, je l'ai eu pleins de fois 
Et je l'ai géré en mettant à chaque fois
`//@ts-expect-error TS ne comprend pas que ces imports sont utilisés`

J'imagine que quand l'équipe TypeScript le corrigera, en mettant à jour TS, on aura de nouvelles erreurs qui nous diront que les `//@ts-expect-error` ne servent à rien et on pourra les enlever à ce moment-là

2025-01-02 18:32 UTC, DavidBruant reviewed
je ne comprends pas bien la danse avec le téléchargement de fichier, la génération d'un json, etc.
Le schema est déjà dans le store côté front-end (`store.state.schemaDS88444`)
et donc, on a déjà la liste des activités prinicipales côté client

(je réalise que c'est ptèt un peu absurde de télécharger le schéma systématiquement pour toutes les pages alors que jusque là, il ne servait que pour les liens de pré-remplissage, mais :shrug:, il est là, donc on peut l'utiliser sans générer un fichier intermédiaire )

Je veux bien en repapoter avant de faire une review plus détaillée

2025-01-02 22:35 UTC, DavidBruant commented on outils/recupère-schema-88444.js
> +/** @import {SchemaDémarcheSimplifiée} from '../scripts/types/démarches-simplifiées/schema.ts' */
J'ai pris le temps de faire un test case réduit et une issue chez TS
https://github.com/microsoft/TypeScript/issues/60908

2025-01-21 12:20 UTC, Ynote commented on scripts/front-end/components/screens/SuiviInstruction.svelte
> +            return _activitésPrincipalesSélectionnées.has(dossier.activité_principale)
J'ai essayé d'ajouter un type sur l'activité principale d'un dossier mais le `extends` n'a pas l'air de fonctionner. Peut-être que je me suis trompée dans la syntaxe. Si tu sais, je veux bien un éclairage. On peut aussi juste laisse le `ts-expect-error`.

2025-01-22 13:45 UTC, DavidBruant commented on scripts/front-end/components/screens/SuiviInstruction.svelte
> +            return _activitésPrincipalesSélectionnées.has(dossier.activité_principale)
Yes, effectivement, le `extends` ne fonctionne pas
Je crois que vu que la propriété est définie à la fois dans `Dossier` et dans `DossierActivitéPrincipale`, TS choisit le premier et ignore le second

J'ai corrigé ça en ajoutant la propriété dans le `Omit`

Et j'ai ajouté un if aussi parce que dans le type issu de DS, `null` n'est pas une option (et dans nos filtres non plus), alors que dans `Dossier` en base de données, `null` est une option

2025-01-22 13:50 UTC, DavidBruant commented on scripts/front-end/components/screens/SuiviInstruction.svelte
> +                        <span class="fr-badge fr-badge--sm">Activités principales : {[...activitésPrincipalesSélectionnées].join(", ")}</span>
Est-ce que ça serait ok pour toi d'utiliser un tag plutôt qu'un badge ?

Je suis parti dans cette direction pour le filtre des instructeurs
https://github.com/betagouv/pitchou/pull/147/files#diff-97122ecb6cbea0b74c0c6cd95e27442a185a75f63a66bb246ec73bc8451d135aR299

2025-01-22 13:51 UTC, DavidBruant reviewed
Trop bien ! 
Merci beaucoup ! 
C'est bon pour moi, modulo l'histoire du badge/tag

2025-01-22 14:12 UTC, DavidBruant requested changes
Ah oui non, pardon ! 
Je crois qu'on en avait parlé à l'oral et j'ai oublié d'en reparler ici

Si on peut chercher par activité principale ici, on peut le retirer de la recherche textuelle

2025-01-22 15:15 UTC, Ynote commented on scripts/front-end/components/screens/SuiviInstruction.svelte
> +                        <span class="fr-badge fr-badge--sm">Activités principales : {[...activitésPrincipalesSélectionnées].join(", ")}</span>
Ah oui, bien sûr bien sûr, c'est mieux, je fais ça !

2025-01-22 15:55 UTC, Ynote commented on scripts/front-end/components/screens/SuiviInstruction.svelte
> +            return _activitésPrincipalesSélectionnées.has(dossier.activité_principale)
Merci 🙏

2025-01-27 10:13 UTC, DavidBruant approved these changes
J'ai corrigé un peu l'aspect visuel des tags des filtres sélectionnés

2025-01-27 10:13 UTC, merged